### ISSUE TITLE
Compost not working

### ISSUE THREAD

**Issue by Toadby** [jummes/MoreCompost#6] opened 2020-03-09 04:21 UTC
Since updating MoreCompost, I still haven't gotten it working unfortunately. The jar says version 2.0.

Whereas before the plugin would not load my compost file into the GUI but would still allow the items to be composted, now it neither shows in the GUI nor works in game.
This is my file:
https://hasteb.in/igufoguq.yaml
I also tried removing the space between the comments and the start of the file, which didn't help.

**Comment by ZamponiMarco** [comment] 2020-03-09 10:23
Duplicate of #4

**Closed as completed by ZamponiMarco** 2020-03-09 10:23 UTC
Labels: duplicate
