### ISSUE TITLE
Permission for player

### ISSUE THREAD

**Issue by GripyCZ** [jummes/MoreCompost#2] opened 2020-02-23 13:37 UTC
Hi, I need help I can't allow players to compost. they cannot compost my own added item and I would like to ask if I need any right - Gripy

**Comment by GripyCZ** [comment] 2020-02-23 13:38
*permission

**Comment by ZamponiMarco** [comment] 2020-03-01 21:29
I'm adding some details on the docs about this

**Comment by ZamponiMarco** [comment] 2020-03-01 21:36
I've added the permission section in the wiki, you can see it here
https://github.com/ZamponiMarco/MoreCompost/wiki#permissions
If it isn't enough let me know, if it's well explained i can close the issue

**Comment by ZamponiMarco** [comment] 2020-03-05 20:58
I assume the problem is solved, closing

**Closed as completed by ZamponiMarco** 2020-03-05 20:58 UTC
Labels: documentation
