### ISSUE TITLE
Compostable added via GUI is showing on the second page.

### ISSUE THREAD

**Issue by Toadby** [jummes/MoreCompost#3] opened 2020-03-01 19:15 UTC
I didn't take a screenshot but at first there were a couple items accidentally added, and they were also on the second page and separated by a few slots rather than next to eachother.
![Screen Shot 2020-03-01 at 11 13 24 AM](https://user-images.githubusercontent.com/16440384/75632114-d2a94580-5bad-11ea-94cb-2b33d07b1895.png)
Version 2.0.

**Comment by ZamponiMarco** [comment] 2020-03-01 21:26
Can i ask you your compostabletable.yml file to replicate the bug?

**Comment by ZamponiMarco** [comment] 2020-03-01 22:00
Ok, it should be fixed actually in 2.0.1, if it works now, I can close the issue, let me know!

**Comment by Toadby** [comment] 2020-03-02 03:05
Unfortunately, updating wiped all items from the GUI.

**Comment by ZamponiMarco** [comment] 2020-03-02 03:09
Can you provide me your compostabletable.yml file?

**Comment by Toadby** [comment] 2020-03-02 04:10
My compostable file was:
https://hastebin.com/lihaxukefo.shell
However, the GUI was not loading these items.
And now after updating, the compostable file is:
https://hastebin.com/yunohayuqa.shell
And the GUI shows neither the items in the file nor the items I added in game before updating.

**Comment by ZamponiMarco** [comment] 2020-03-02 13:01
I moved this issue to a new issue  #4, since the problem is different, I close this since the fact that compostables go on the second page is solved, let's talk about this there, for clarity!

**Closed as completed by ZamponiMarco** 2020-03-02 13:01 UTC
Labels: bug
